CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  salt TEXT NOT NULL,
  ho_ten TEXT,
  role TEXT DEFAULT 'owner' CHECK (role IN ('owner', 'staff')),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten TEXT NOT NULL,
  dien_thoai TEXT UNIQUE NOT NULL,
  email TEXT,
  ghi_chu TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  ho_ten TEXT NOT NULL,
  dien_thoai TEXT NOT NULL,
  email TEXT,
  diem_lay_hang TEXT NOT NULL,
  diem_giao_hang TEXT NOT NULL,
  loai_hang TEXT,
  trong_luong DOUBLE PRECISION,
  ghi_chu TEXT,
  gia_tri DOUBLE PRECISION,
  trang_thai TEXT DEFAULT 'moi' CHECK (trang_thai IN ('moi', 'da_bao_gia', 'dang_chay', 'hoan_thanh', 'huy')),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten TEXT NOT NULL,
  bien_so TEXT UNIQUE NOT NULL,
  loai TEXT,
  tai_trong TEXT,
  trang_thai TEXT DEFAULT 'san_sang' CHECK (trang_thai IN ('san_sang', 'dang_chay', 'bao_duong')),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
  vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE SET NULL,
  tai_xe TEXT,
  ngay_khoi_hanh TEXT,
  trang_thai TEXT DEFAULT 'cho_chay' CHECK (trang_thai IN ('cho_chay', 'dang_chay', 'hoan_thanh', 'huy')),
  ghi_chu TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bookings_customer_id ON bookings(customer_id);
CREATE INDEX IF NOT EXISTS idx_bookings_created_at ON bookings(created_at);
CREATE INDEX IF NOT EXISTS idx_trips_booking_id ON trips(booking_id);
CREATE INDEX IF NOT EXISTS idx_trips_vehicle_id ON trips(vehicle_id);
